version: "3.4"
services:
  go-there:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./go-there.conf:/bin/go-there.conf
    networks:
      - go-there_network
  mysql:
    image: mysql:8
    volumes:
      - ./db/go-there.sql:/docker-entrypoint-initdb.d/go-there.sql
    environment:
      MYSQL_ROOT_PASSWORD: superrootpassword
      MYSQL_DATABASE: go_there_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: superpassword
    networks:
      - go-there_testing
  redis:
    image: redis:6-alpine
networks:
  go-there_network: